---
title: GBergeret Cloud Services
description: |
  GBergeret cloud Services website, a place to share my values, background,
  skills and contact details.
url: "https://gbergeret.cloud"
baseurl: ""

author:
  name: Geoffrey Bergeret
  email: geoffrey@gbergeret.cloud
  phone: +44 7871 334653
  linkedin: gbergere
  github: gbergere

company:
  name: GBergeret Cloud Services
  number: 12543938
  address:
    - 85 Great Portland Street, First Floor,
    - London, W1W 7LT, United Kingdom
  vat_number: GB353207815
  email: contact@gbergeret.cloud
  linkedin: gbergeret-cloud
  github: gbergeret-cloud

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .docker-compose.yml
  - .git
  - .github
  - .editorconfig
  - CNAME
  - README.md

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title:output_ext

defaults:
  - scope:
      path: ""
    values:
      layout: "base"
